version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_list_container
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db-init:
    build:
      context: ..
      dockerfile: docker/postgres/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../.env
    environment:
      - POSTGRES_HOST=db
      - PYTHONPATH=/app
    profiles:
      - init

  db-test:
    image: postgres:15
    container_name: postgres_test_container
    tmpfs:
      - /var/lib/postgresql/test
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test_user", "-d", "test_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - test

  fga-db:
    image: postgres:15
    container_name: openfga_postgres
    environment:
      - POSTGRES_USER=openfga_user
      - POSTGRES_PASSWORD=openfga_pass
      - POSTGRES_DB=openfga_db
    volumes:
      - ./postgres/fga-data:/var/lib/postgresql/data
    ports:
      - "55432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "openfga_user", "-d", "openfga_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - init

  migrate-fga:
    image: openfga/openfga:v1.5.3
    container_name: openfga_migrate
    depends_on:
      fga-db:
        condition: service_healthy
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://openfga_user:openfga_pass@fga-db:5432/openfga_db?sslmode=disable
    command: migrate
    profiles:
      - init

  openfga:
    depends_on:
      migrate-fga:
        condition: service_completed_successfully
    image: openfga/openfga:v1.5.3
    container_name: openfga
    command: run
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://openfga_user:openfga_pass@fga-db:5432/openfga_db?sslmode=disable
      - OPENFGA_DATASTORE_MAX_OPEN_CONNS=100
      - OPENFGA_PLAYGROUND_ENABLED=true
    ports:
      - "8080:8080"
      - "8089:8081"
      - "3000:3000"
      - "2112:2112"
    healthcheck:
      test: [ "CMD", "/usr/local/bin/grpc_health_probe", "-addr=localhost:8081" ]
      interval: 5s
      timeout: 30s
      retries: 3
    profiles:
      - init

volumes:
  postgres_data:
  fga_data:
